# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/msm8916-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/adsprpcd:vendor/bin/adsprpcd \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/irsc_util:vendor/bin/irsc_util \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/netmgrd:vendor/bin/netmgrd \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/qmi_motext_hook:vendor/bin/qmi_motext_hook \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/qmuxd:vendor/bin/qmuxd \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/qseecomd:vendor/bin/qseecomd \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/radish:vendor/bin/radish \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/rmt_storage:vendor/bin/rmt_storage \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/DR_AP_Service:vendor/bin/DR_AP_Service \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/garden_app:vendor/bin/garden_app \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/loc_launcher:vendor/bin/loc_launcher \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/lowi-server:vendor/bin/lowi-server \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/time_daemon:vendor/bin/time_daemon \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/thermal-engine:vendor/bin/thermal-engine \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/slim_daemon:vendor/bin/slim_daemon \
    vendor/motorola/msm8916-common/proprietary/vendor/bin/xtra-daemon:vendor/bin/xtra-daemon \
    vendor/motorola/msm8916-common/proprietary/vendor/framework/com.qti.location.sdk.jar:vendor/framework/com.qti.location.sdk.jar \
    vendor/motorola/msm8916-common/proprietary/vendor/framework/izat.xt.srv.jar:vendor/framework/izat.xt.srv.jar \
    vendor/motorola/msm8916-common/proprietary/vendor/etc/xtra_root_cert.pem:vendor/etc/xtra_root_cert.pem \
    vendor/motorola/msm8916-common/proprietary/vendor/etc/data/dsi_config.xml:vendor/etc/data/dsi_config.xml \
    vendor/motorola/msm8916-common/proprietary/vendor/etc/data/netmgr_config.xml:vendor/etc/data/netmgr_config.xml \
    vendor/motorola/msm8916-common/proprietary/vendor/etc/data/qmi_config.xml:vendor/etc/data/qmi_config.xml \
    vendor/motorola/msm8916-common/proprietary/vendor/etc/permissions/com.qti.location.sdk.xml:vendor/etc/permissions/com.qti.location.sdk.xml \
    vendor/motorola/msm8916-common/proprietary/vendor/etc/permissions/izat.xt.srv.xml:vendor/etc/permissions/izat.xt.srv.xml \
    vendor/motorola/msm8916-common/proprietary/vendor/etc/permissions/qcnvitems.xml:vendor/etc/permissions/qcnvitems.xml \
    vendor/motorola/msm8916-common/proprietary/vendor/etc/permissions/qcrilhook.xml:vendor/etc/permissions/qcrilhook.xml \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/sensorhubfw.bin:vendor/firmware/sensorhubfw.bin \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/sensorhubver.txt:vendor/firmware/sensorhubver.txt \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/venus.b00:vendor/firmware/venus.b00 \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/venus.b01:vendor/firmware/venus.b01 \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/venus.b02:vendor/firmware/venus.b02 \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/venus.b03:vendor/firmware/venus.b03 \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/venus.b04:vendor/firmware/venus.b04 \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/venus.mbn:vendor/firmware/venus.mbn \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/venus.mdt:vendor/firmware/venus.mdt \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/a300_pfp.fw:vendor/firmware/a300_pfp.fw \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/a300_pm4.fw:vendor/firmware/a300_pm4.fw \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/a420_pfp.fw:vendor/firmware/a420_pfp.fw \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/a420_pm4.fw:vendor/firmware/a420_pm4.fw \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:vendor/firmware/cpp_firmware_v1_1_1.fw \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:vendor/firmware/cpp_firmware_v1_1_6.fw \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:vendor/firmware/cpp_firmware_v1_2_0.fw \
    vendor/motorola/msm8916-common/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:vendor/firmware/cpp_firmware_v1_4_0.fw \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/com.qualcomm.qti.bluetooth_audio@1.0_vendor.so:vendor/lib/com.qualcomm.qti.bluetooth_audio@1.0_vendor.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/eglsubAndroid.so:vendor/lib/egl/eglsubAndroid.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/libEGL_adreno.so:vendor/lib/egl/libEGL_adreno.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/libESXEGL_adreno.so:vendor/lib/egl/libESXEGL_adreno.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/libGLESv2_adreno.so:vendor/lib/egl/libGLESv2_adreno.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/libQTapGLES.so:vendor/lib/egl/libQTapGLES.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/libRBEGL_adreno.so:vendor/lib/egl/libRBEGL_adreno.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/libq3dtools_adreno.so:vendor/lib/egl/libq3dtools_adreno.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/egl/libq3dtools_esx.so:vendor/lib/egl/libq3dtools_esx.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/hw/android.hardware.bluetooth@1.0-impl-qti.so:vendor/lib/hw/android.hardware.bluetooth@1.0-impl-qti.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/hw/vendor.qti.hardware.fm@1.0-impl.so:vendor/lib/hw/vendor.qti.hardware.fm@1.0-impl.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libApeSwDec.so:vendor/lib/libApeSwDec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libFlacSwDec.so:vendor/lib/libFlacSwDec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libMpeg4SwEncoder.so:vendor/lib/libMpeg4SwEncoder.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxAlacDec.so:vendor/lib/libOmxAlacDec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxAlacDecSw.so:vendor/lib/libOmxAlacDecSw.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxAmrwbplusDec.so:vendor/lib/libOmxAmrwbplusDec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxApeDec.so:vendor/lib/libOmxApeDec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxApeDecSw.so:vendor/lib/libOmxApeDecSw.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxDsdDec.so:vendor/lib/libOmxDsdDec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxSwVdec.so:vendor/lib/libOmxSwVdec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxAmrDec.so:vendor/lib/libOmxAmrDec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxSwVencMpeg4.so:vendor/lib/libOmxSwVencMpeg4.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxVpp.so:vendor/lib/libOmxVpp.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxWmaDec.so:vendor/lib/libOmxWmaDec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libC2D2.so:vendor/lib/libC2D2.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libCB.so:vendor/lib/libCB.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libDiagService.so:vendor/lib/libDiagService.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/lib_drplugin_server.so:vendor/lib/lib_drplugin_server.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libDRPlugin.so:vendor/lib/libDRPlugin.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libFileMux.so:vendor/lib/libFileMux.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libI420colorconvert.so:vendor/lib/libI420colorconvert.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libmmosal.so:vendor/lib/libmmosal.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxAacDec.so:vendor/lib/libOmxAacDec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxEvrcDec.so:vendor/lib/libOmxEvrcDec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOmxQcelp13Dec.so:vendor/lib/libOmxQcelp13Dec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libOpenCL.so:vendor/lib/libOpenCL.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libQSEEComAPI.so:vendor/lib/libQSEEComAPI.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libRSDriver_adreno.so:vendor/lib/libRSDriver_adreno.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libSubSystemShutdown.so:vendor/lib/libSubSystemShutdown.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libTimeService.so:vendor/lib/libTimeService.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libacdb-fts.so:vendor/lib/libacdb-fts.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libloc_api_v02.so:vendor/lib/libloc_api_v02.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libloc_ds_api.so:vendor/lib/libloc_ds_api.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libacdbloader.so:vendor/lib/libacdbloader.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libacdbrtac.so:vendor/lib/libacdbrtac.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libadiertac.so:vendor/lib/libadiertac.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libadreno_utils.so:vendor/lib/libadreno_utils.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libadsprpc.so:vendor/lib/libadsprpc.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libaptX_encoder.so:vendor/lib/libaptX_encoder.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libaptXHD_encoder.so:vendor/lib/libaptXHD_encoder.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libaudcal.so:vendor/lib/libaudcal.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libbccQTI.so:vendor/lib/libbccQTI.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libbson.so:vendor/lib/libbson.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libbtnv.so:vendor/lib/libbtnv.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libc2d30-a3xx.so:vendor/lib/libc2d30-a3xx.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libc2d30_bltlib.so:vendor/lib/libc2d30_bltlib.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libc2d30-a5xx.so:vendor/lib/libc2d30-a5xx.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libc2d30-a4xx.so:vendor/lib/libc2d30-a4xx.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libfacenet-32.so:vendor/lib/libfacenet-32.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libcneapiclient.so:vendor/lib/libcneapiclient.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libconfigdb.so:vendor/lib/libconfigdb.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libdataitems.so:vendor/lib/libdataitems.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libdiag.so:vendor/lib/libdiag.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libdrmfs.so:vendor/lib/libdrmfs.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libdrmtime.so:vendor/lib/libdrmtime.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libdrplugin_client.so:vendor/lib/libdrplugin_client.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libdsi_netctrl.so:vendor/lib/libdsi_netctrl.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libdsutils.so:vendor/lib/libdsutils.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libevent_observer.so:vendor/lib/libevent_observer.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libfastcvopt.so:vendor/lib/libfastcvopt.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libflp.so:vendor/lib/libflp.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libgdtap.so:vendor/lib/libgdtap.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libgeofence.so:vendor/lib/libgeofence.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libgsl.so:vendor/lib/libgsl.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libHevcSwDecoder.so:vendor/lib/libHevcSwDecoder.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libidl.so:vendor/lib/libidl.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libizat_client_api.so:vendor/lib/libizat_client_api.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libizat_core.so:vendor/lib/libizat_core.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/liblbs_core.so:vendor/lib/liblbs_core.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libldacBT_enc.so:vendor/lib/libldacBT_enc.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libllvm-glnext.so:vendor/lib/libllvm-glnext.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libllvm-qcom.so:vendor/lib/libllvm-qcom.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libloc_api_v02.so:vendor/lib/libloc_api_v02.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libloc_ds_api.so:vendor/lib/libloc_ds_api.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libloc_externalDr.so:vendor/lib/libloc_externalDr.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/liblowi_wifihal.so:vendor/lib/liblowi_wifihal.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/liblqe.so:vendor/lib/liblqe.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libhdr_tm.so:vendor/lib/libhdr_tm.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libomx-dts.so:vendor/lib/libomx-dts.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/librilutils.so:vendor/lib/librilutils.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/motcamera.device@1.0-impl.so:vendor/lib/motcamera.device@1.0-impl.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libmdmdetect.so:vendor/lib/libmdmdetect.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libmm-color-convertor.so:vendor/lib/libmm-color-convertor.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libmm-disp-apis.so:vendor/lib/libmm-disp-apis.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libmm-hdcpmgr.so:vendor/lib/libmm-hdcpmgr.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libmm-qdcm.so:vendor/lib/libmm-qdcm.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libmmQSM.so:vendor/lib/libmmQSM.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libmmosal_proprietary.so:vendor/lib/libmmosal_proprietary.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libnetmgr.so:vendor/lib/libnetmgr.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libprotobuf-cpp-haxx.so:vendor/lib/libprotobuf-cpp-haxx.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libperipheral_client.so:vendor/lib/libperipheral_client.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqcci_legacy.so:vendor/lib/libqcci_legacy.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libquipc_os_api.so:vendor/lib/libquipc_os_api.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqct_resampler.so:vendor/lib/libqct_resampler.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqdi.so:vendor/lib/libqdi.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqdp.so:vendor/lib/libqdp.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqmi.so:vendor/lib/libqmi.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqmi_cci.so:vendor/lib/libqmi_cci.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqmi_client_helper.so:vendor/lib/libqmi_client_helper.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqmi_client_qmux.so:vendor/lib/libqmi_client_qmux.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqmi_common_so.so:vendor/lib/libqmi_common_so.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqmi_csi.so:vendor/lib/libqmi_csi.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqmi_encdec.so:vendor/lib/libqmi_encdec.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqmiservices.so:vendor/lib/libqmiservices.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libril-qc-ltedirectdisc.so:vendor/lib/libril-qc-ltedirectdisc.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libril-qc-qmi-1.so:vendor/lib/libril-qc-qmi-1.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libril-qc-radioconfig.so:vendor/lib/libril-qc-radioconfig.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libril-qcril-hook-oem.so:vendor/lib/libril-qcril-hook-oem.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/librilqmiservices.so:vendor/lib/librilqmiservices.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/librpmb.so:vendor/lib/librpmb.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/librs_adreno.so:vendor/lib/librs_adreno.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/librs_adreno_sha1.so:vendor/lib/librs_adreno_sha1.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libsc-a3xx.so:vendor/lib/libsc-a3xx.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libscale.so:vendor/lib/libscale.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libsettings.so:vendor/lib/libsettings.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libsmemlog.so:vendor/lib/libsmemlog.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libslimclient.so:vendor/lib/libslimclient.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libssd.so:vendor/lib/libssd.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libstlport.so:vendor/lib/libstlport.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libsubsystem_control.so:vendor/lib/libsubsystem_control.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libsystem_health_mon.so:vendor/lib/libsystem_health_mon.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libthermalclient.so:vendor/lib/libthermalclient.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libthermalioctl.so:vendor/lib/libthermalioctl.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libtime_genoff.so:vendor/lib/libtime_genoff.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libvoice-svc.so:vendor/lib/libvoice-svc.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libxml.so:vendor/lib/libxml.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/vendor.qti.gnss@1.0_vendor.so:vendor/lib/vendor.qti.gnss@1.0_vendor.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/soundfx/libqcbassboost.so:vendor/lib/soundfx/libqcbassboost.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/soundfx/libqcreverb.so:vendor/lib/soundfx/libqcreverb.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/soundfx/libqcvirt.so:vendor/lib/soundfx/libqcvirt.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/soundfx/libatmos.so:vendor/lib/soundfx/libatmos.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/soundfx/libswvlldp.so:vendor/lib/soundfx/libswvlldp.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/motorola.hardware.camera.device@1.0_vendor.so:vendor/lib/motorola.hardware.camera.device@1.0_vendor.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/motorola.hardware.camera.provider@2.4_vendor.so:vendor/lib/motorola.hardware.camera.provider@2.4_vendor.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/hw/vendor.qti.gnss@1.0-impl.so:vendor/lib/hw/vendor.qti.gnss@1.0-impl.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/vendor.qti.hardware.fm@1.0_vendor.so:vendor/lib/vendor.qti.hardware.fm@1.0_vendor.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/vendor.qti.hardware.radio.qcrilhook@1.0_vendor.so:vendor/lib/vendor.qti.hardware.radio.qcrilhook@1.0_vendor.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libadropbox.so:vendor/lib/libadropbox.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/liblocationservice_jni.so:vendor/lib/liblocationservice_jni.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libmdmcutback.so:vendor/lib/libmdmcutback.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libmot_sensorlistener.so:vendor/lib/libmot_sensorlistener.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libmotext_inf.so:vendor/lib/libmotext_inf.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/libqmimotext.so:vendor/lib/libqmimotext.so \
    vendor/motorola/msm8916-common/proprietary/vendor/lib/vendor.qti.gnss@1.0.so:vendor/lib/vendor.qti.gnss@1.0.so \
    vendor/motorola/msm8916-common/proprietary/vendor/qcril.db:vendor/qcril.db

PRODUCT_PACKAGES += \
    vendor.qti.hardware.fm@1.0 \
    TimeService \
    qcrilmsgtunnel \
    qcnvitems \
    qcrilhook



